### ISSUE TITLE
Fix scramsha migration test failures on rails 7.1

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq-schema#768]
From https://github.com/ManageIQ/manageiq-schema/pull/767
Seen in https://github.com/ManageIQ/manageiq-schema/pull/766

```
1) ReencryptPasswordScramsha#up Ensures that the user password is stored as scram-sha-256
     Failure/Error: expect(ActiveRecord::Base.connection_db_config).to receive(:configuration_hash).exactly(10).times.and_call_original

       (#<ActiveRecord::DatabaseConfigurations::HashConfig:0x00007f4cdb38ad18 @env_name="test", @name="primary", @configuration_hash={:adapter=>"postgresql", :encoding=>"utf8", :username=>"root", :***"smartvm", :pool=>3, :wait_timeout=>5, :min_messages=>"warning", :database=>"dummy_test"}>).configuration_hash(*(any args))
           expected: 10 times with any arguments
           received: 1 time with any arguments
     # ./spec/migrations/20241017013023_reencrypt_password_scramsha_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/support/migration_helper.rb:77:in `clearing_caches'
     # ./spec/support/migration_helper.rb:13:in `block (2 levels) in migration_context'

  2) ReencryptPasswordScramsha#up Handles connections with no password
     Failure/Error: super

       (#<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00007f4cda51acb0 @transaction_manager=#<ActiveRecord::ConnectionAdapters::TransactionManager:0x00007f4cda920a80 @stack=[#<ActiveRecord::ConnectionAdapters::RealTransaction:0x00007f4cd3e9c[47](https://github.com/ManageIQ/manageiq-schema/actions/runs/11858845607/job/33050405714?pr=766#step:6:48)0 @connection=#<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00007f4cda51acb0 ...>, @state=#<ActiveRecord::ConnectionAdapters::TransactionState:0x00007f4cd3e9c420 @state=nil, @children=[#<ActiveRecord::ConnectionAdapters::TransactionState:0x00007f4cd395a930 @state=nil, @children=nil>]>, @records=nil, @isolation_level=nil, @materialized=true, @joinable=false, @run_commit_callbacks=true, @lazy_enrollment_records=nil, @dirty=true, @instrumenter=#<ActiveRecord::ConnectionAdapters::TransactionInstrumenter:0x00007f4cd3e9c290 @handle=#<ActiveSupport::Notifications::Fanout::Handle:0x00007f4cd3ea1718 @name="transaction.active_record", @id="4321fe7d6758014edd25", @payload={:connection=>#<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00007f4cda[51](https://github.com/ManageIQ/manageiq-schema/actions/runs/11858845607/job/33050405714?pr=766#step:6:52)acb0 ...>}, @groups=[],
```

**Comment by Fryguy** [comment]
cc @bdunne
